# Generated by Django 6.0.5 on 2026-06-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
    ]
